version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.2.1
    ports:    
      - "3100:3100"
    volumes:
      - /Users/balut/monitoring/grafana/loki-config.yml:/etc/loki/loki-config.yml      
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - /Users/balut/monitoring/grafana/promtail-config.yml:/etc/promtail/docker-config.yml
    command: -config.file=/etc/promtail/docker-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki

  nginxapp:
    image: nginx
    ports:
      - "8080:80"
    networks:
      - loki      