on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Parent pipeline
    steps:
      - uses: actions/checkout@v4     
      - id: foo
        name: Invoke the child pipeline
        uses: ./
        with:
          who-to-greet: 'Balu'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        name: print random number
        shell: bash
