name: Workflow A

on:
  push:
    branches: [ "test" ]

jobs:
  upload_Artifact:  
    runs-on: ubuntu-latest
    steps:
      - name: create Json
        run: |
            printf '{ 
              "prop_1": "Balu",  
              "prop_2": "updated"
            }' >> context.json
      - uses: actions/upload-artifact@v3
        with:
          name: context.json
          path: ./
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 14.x
          cache: ''
          
