name: Parent pipeline
on:
  issues:
    types:
      - opened
      - edited
jobs:
  build:
    uses: balakrishna222111/100DaysofDevops/.github/workflows/workfow.yml@main
    with:
      input1: Balu
