name: Workflow A

on:
  push:
    branches: [ "main" ]

jobs:
  upload_Artifact:  
    runs-on: ubuntu-latest
    outputs:
      step_output: ${{ steps.upload_Artifact.outputs.variable_value }}
    steps:
      - name: create Json
        run: |
            printf '{ 
              "prop_1": "Balu",  
              "prop_2": "updated"
            }' >> context.json
      - uses: actions/upload-artifact@v3
        with:
          name: context.json
          path: ./
      - name: Set Environment Variable
        run: echo "BALU=catchme" >> $GITHUB_ENV
  
  fetch_variable:
      needs: upload_Artifact
      runs-on: ubuntu-latest
  
      steps:
      - name: Use Environment Variable
        run: echo "Variable Value ${{ needs.upload_Artifact.outputs.step_output }}"
