on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Parent pipeline
    steps:
      - uses: actions/checkout@v4
      - name: Set execute permissions for goodbye.sh
        run: chmod +x goodbye.sh
      - name: Run goodbye.sh
        run: ./goodbye.sh      
      - id: foo
        name: Invoke the child pipeline
        uses: ./
        with:
          who-to-greet: 'Balu'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
