on:
  issues:
    types:
      - opened
      - edited

jobs:
  random_number_job:
    runs-on: ubuntu-latest
    name: Parent pipeline
    steps:
      - uses: actions/checkout@v4     
      - id: childPipeline
        name: Invoke the child pipeline
        uses: ./
        with:
          who-to-greet: 'Balu'
      - run: echo random-number ${{ steps.childPipeline.outputs.random-number }}
        name: print random number
        shell: bash
      - name: Print Issue Number
        run: |
          echo "GitHub Issue Number: ${{ github.event.issue.number }}"
      - name: Post Comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const randomNumber = "${{ steps.childPipeline.outputs.random-number }}";
            const comment = `The random number is: ${randomNumber}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
      - name: Add Label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Red']  
            });
