name: Parent pipeline
on:
  issues:
    types:
      - opened
      - edited

jobs:
  random_number_job:
    runs-on: ubuntu-latest
    name: Parent pipeline
    outputs:
      issue-number: ${{ needs.childPipeline.outputs.issue-number }}    
    steps:
      - uses: actions/checkout@v4     
      - id: childPipeline
        name: Invoke the child pipeline
        uses: ./
        with:
          who-to-greet: 'Balu'
          issue-number: ${{ github.event.issue.number }}
      - run:  echo "Random number from child pipeline ${{ needs.childPipeline.outputs.random-number }}"
        name: print random number
        shell: bash
      - name: Set Environment Variable
        run: echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
      - run: echo "Issue number from child pipeline $ISSUE_NUMBER"
        name: print issue number
        shell: bash
      - name: Post Comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const randomNumber = "${{ steps.childPipeline.outputs.random-number }}";
            const comment = `The random number is: ${randomNumber}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
      - name: Add Label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Red']  
            });
      - run: echo "Issue number from Parent pipeline $ISSUE_NUMBER"
        name: print issue number
        shell: bash
  test:
    needs: "random_number_job"
    runs-on: ubuntu-latest
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: 2
      - run: |
          echo ${{ steps.fc.outputs.comment-body }}
      - name: Install jq
        run: sudo apt-get install jq
      - name: Get Last Comment
        id: last-comment
        uses: octokit/request-action@v2.x
        with:
          route: GET "/repos/balakrishna222111/100DaysofDevops/issues/2/comments"
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue_number: ${{ github.event.issue.number }}
      - run: |
          # Extract the last comment details
          lastCommentId=$(echo "${{ steps.last-comment.outputs.data }}" | jq '.[-1].id')
          lastCommentBody=$(echo "${{ steps.last-comment.outputs.data }}" | jq -r '.[-1].body')
          lastCommentAuthor=$(echo "${{ steps.last-comment.outputs.data }}" | jq -r '.[-1].user.login')
          lastCommentCreatedAt=$(echo "${{ steps.last-comment.outputs.data }}" | jq -r '.[-1].created_at')
          echo "Last Comment ID: $lastCommentId"
          echo "Last Comment Body: $lastCommentBody"
          echo "Last Comment Author: $lastCommentAuthor"
          echo "Last Comment Created At: $lastCommentCreatedAt"

