name: Workflow A

on:
  push:
    branches: [ "main" ]

jobs:
  upload_Artifact:  
    runs-on: ubuntu-latest
    steps:
      - name: create Json
        run: |
            printf '{ 
              "prop_1": "Balu",  
              "prop_2": "updated"
            }' >> context.json
      - uses: actions/upload-artifact@v3
        with:
          name: context.json
          path: ./
