on:
  issues:
    types:
      - opened

jobs:
  random_number_job:
    runs-on: ubuntu-latest
    name: Parent pipeline
    steps:
      - uses: actions/checkout@v4     
      - id: childPipeline
        name: Invoke the child pipeline
        uses: ./
        with:
          who-to-greet: 'Balu'
      - run: echo random-number ${{ steps.childPipeline.outputs.random-number }}
        name: print random number
        shell: bash
