name: Set Branch Protection

on:
  workflow_dispatch: 

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: |
          sudo apt-get install gh -y

      - name: Apply branch protection rules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GITHUB_TOKEN}"
          gh api --method PUT /repos/${{ github.repository }}/branches/main/protection \
            -F required_status_checks='{"strict":true,"contexts":["ci-build"]}' \
            -F enforce_admins=true \
            -F required_pull_request_reviews='{"required_approving_review_count":2}' \
            -F restrictions='{"users":["user1"],"teams":["team1"]}'
