
name: Set Branch Protection

on:
  push:
    branches:
      - main

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PAT }}" | gh auth login --with-token
          # gh api \
          # -H "Accept: application/vnd.github+json" \
          # -H "X-GitHub-Api-Version: 2022-11-28" \
          # /repos/balakrishna222111/100DaysofDevops/branches/users/bala/protection 

      - name: Apply branch protection rules
        run: |
          gh api --method PUT /repos/balakrishna222111/100DaysofDevops/branches/users/bala/protection \
            -F enforce_admins=true \
            -F required_status_checks='{"strict":true,"contexts":["ci-build"]}' \
            -F dismissal_restrictions='{"users":["octocat"],"teams":["justice-league"]}' \
            -F required_pull_request_reviews='{"dismiss_stale_reviews":true,"require_code_owner_reviews":true,"required_approving_review_count":2,"require_last_push_approval":true}' \
            -F bypass_pull_request_allowances='{"users":["octocat"],"teams":["justice-league"]}' \
            -F restrictions='{"users":["octocat"],"teams":["justice-league"],"apps":["super-ci"]}' \
            -F required_linear_history=true \
            -F allow_force_pushes=false \
            -F allow_deletions=false \
            -F block_creations=true \
            -F required_conversation_resolution=true \
            -F lock_branch=false \
            -F allow_fork_syncing=true

