name: Child Pipeline

on:
  workflow_run:
    workflows: ["Parent pipeline"]
    types:
      - completed

jobs:
  fetch_comment_job:
    runs-on: ubuntu-latest
    outputs:
      random-number: ${{ steps.generateRandomNumber.outputs.random-number }}
    steps:
      - name: Generate Random Number
        id: generateRandomNumber
        run: echo "::set-output name=random-number::${{ github.run_id }}"
      - name: Print Comment
        run: echo "Fetched Comment ${{ steps.fetchComment.outputs }}"
      - name: Print Issue Number
        run: |
          echo "GitHub Issue Number ${{ github.event.issue.number }}"
      - name: Print Issue Number
        run: |
          echo "GitHub Issue Number $ISSUE_NUMBER"
      - name: Print Latest Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: comments } = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            if (comments.length > 0) {
              const latestComment = comments[comments.length - 1];
              console.log(`Latest Comment: ${latestComment.body}`);
            } else {
              console.log('No comments on this issue.');
            }          
