name: Child Pipeline

on:
  workflow_run:
    workflows: ["Parent pipeline"]
    types:
      - completed

jobs:
  fetch_comment_job:
    runs-on: ubuntu-latest
    outputs:
      random-number: ${{ steps.generateRandomNumber.outputs.random-number }}
    steps:
      - name: Generate Random Number
        id: generateRandomNumber
        run: echo "::set-output name=random-number::${{ github.run_id }}"
      - name: Print Comment
        run: echo "Fetched Comment ${{ steps.fetchComment.outputs }}"
      - name: Print Issue Number
        run: |
          echo "GitHub Issue Number ${{ github.event.issue.number }}"
      - name: Print Issue Number
        run: |
          echo "GitHub Issue Number $ISSUE_NUMBER"
   
