name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:  
  download_context_artifact:
    runs-on: ubuntu-latest
    outputs:
      variable_value_workflow_B: ${{ steps.set-output-workflow-B.outputs.variable_value_workflow_B }}
    steps:
      - name: 'Set Output Variable in Workflow B'
        id: set-output-workflow-B
        run: echo "::set-output name=variable_value_workflow_B::my_value"

  run_on_workflow_a_success:
    needs: download_context_artifact
    runs-on: ubuntu-latest
    steps:
      - name: Run on workflow A success
        run: echo "Workflow A completes successfully"

  # some_other_job:
  #   needs: download_context_artifact
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Use Output Variable in Workflow B
  #       run: echo "Output Variable variable_value_workflow_B: ${{ needs.download_context_artifact.outputs.variable_value_workflow_B }}"
