name: Workflow B

on:
  workflow_run:
    workflows: ["Parent pipeline"]
    types:
      - completed

jobs:
  fetch_comment_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Comment
        run: echo "Fetched Comment ${{ steps.fetchComment.outputs }}"
