name: Workflow B

on:
  workflow_run:
    workflows: ["Parent pipeline"]
    types:
      - completed

jobs:
  fetch_comment_job:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Comment
        id: fetchComment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commentUrl = "${{ github.event.workflow_run.event.comment_url }}";
            const commentId = commentUrl.split('/').pop();
            const comment = github.issues.getComment({
              comment_id: commentId,
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return comment.data.body;
      - name: Print Comment
        run: echo "Fetched Comment ${{ steps.fetchComment.outputs }}"
